# Generated by Django 2.2.3 on 2019-07-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('slug', models.SlugField(help_text='A label for URL', max_length=63, unique_for_month='pub_date')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('startup', models.ManyToManyField(to='organiser.Startup')),
                ('tags', models.ManyToManyField(to='organiser.Tag')),
            ],
            options={
                'verbose_name': 'blog post',
                'ordering': ['pub_date', 'title'],
                'get_latest_by': 'pub_date',
            },
        ),
    ]
