# Generated by Django 2.2.5 on 2019-12-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190805_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='startup',
            new_name='startups',
        ),
    ]
